Vagrant.configure("2") do |config|

	config.vm.box = "ubuntu/bionic64"

	config.vm.provider "virtualbox" do |vb|

		vb.memory = 4096
		vb.cpus = 2

	end

	# vNic
	config.vm.network "private_network", ip: "192.168.33.10"

	# Shared folder
	config.vm.synced_folder "workspace/", "/home/vagrant/workspace", create: true

end