- name: Install_pip
  tags: install_pip
  apt:
    name: python3-pip
    state: present

- name: Install_python_modules_for_docker
  tags: install_python_modules
  pip:
    name: "{{item.name}}"
    executable: pip3
    version: "{{item.version}}"
    state: present
  with_items:
  - { name: docker, version: 2.0.0 }
  - { name: docker-py, version: 1.10.6 }

# https://docs.ansible.com/ansible/latest/collections/community/docker/docker_container_module.html#ansible-collections-community-docker-docker-container-module
- name: Create_mariaDB_container
  tags: create_mariadb
  docker_container:   # a besoin de pip + modules py pour fonctionner (voir lignes 1 à 16)
    name: mariaDB
    image: mariadb    # latest puisque pas précisé
    state: started
    forcekill: yes
    restart: yes
    ports:
      - 3306:3306
    env:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ansible